wallpaper {
    monitor = DP-1
    path = ~/Pictures/wallpapers/wallhaven-3q9qky_3840x2160.png
    fit_mode = cover
}

wallpaper {
    monitor = eDP-1
    path = ~/Pictures/wallpapers/wallhaven-3q9qky_1920x1080.png
    fit_mode = cover
}

splash = false
